### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Grusin99**
Guids claim 1.900.000.000 – 1.955.999.999

### CODE REVIEW

**Comment by taubenangriff** [comment]
That's a pretty sizable amount of guids, are you sure you need 55 million of them?

**Comment by jakobharder** [comment]
It took me one year to use 1000 😄

**Comment by Grusin99** [comment]
Sie können besser zählen :) Mir reichen dann
1.900.000.000 bis 1.900.009.999 völlig aus. Danke!

**Comment by Serpens66** [comment]
added: https://github.com/anno-mods/GuidRanges/commit/bb0b8b427fb4d342c4b5cd500639ee931a4ff6e9

**Pull request closed without merging**
